version: '3'
services:
  apigateway:
    image: amolknexaitech/apigateway:latest
    # build: ./apigateway
    ports:
      - "3000:3000"
  potdargroupbackend:
    # build: ./potdargroupbackend
    image: amolknexaitech/potdargroupbackend:latest
    ports:
      - "4000:4000"

  dynamicbackend:
    # build: ./dynamicbackend
    image: amolknexaitech/dynamicbackend:latest
    ports:
      - "5000:5000"

  randomwebsite:
    image: amolknexaitech/randomwebsite
    ports:
      - "6000:6000"

# amolknexaitech

