name: main.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use a valid Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build and push Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.CICDNODE }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker build -t amolknexaitech/apigateway:latest .
          docker push amolknexaitech/apigateway:latest
          docker build -t amolknexaitech/potdargroupbackend:latest .
          docker push amolknexaitech/potdargroupbackend:latest
          docker build -t amolknexaitech/amolknexaitech/dynamicbackend:latest .
          docker push amolknexaitech/amolknexaitech/dynamicbackend:latest
          docker build -t amolknexaitech/amolknexaitech/randomwebsite:latest .
          docker push amolknexaitech/amolknexaitech/randomwebsite:latest

      - name: Deploy microservices
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.CICDNODE }}
        run: |
          # Deploy microservice using Docker Compose or Kubernetes, depending on your setup
          # Example:
          # docker-compose up -d
          # or
          # kubectl apply -f deployment.yaml

      - name: Run tests
        run: npm test # Ensure your tests are properly configured and will run successfully
