name: main.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build and push Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.CICDNODE }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker build -t apigateway:latest      ./apigateway
          docker push amolknexaitech/apigateway:latest

          docker build -t potdargroupbackend:latest  ./PotdarGroup_admin_panel
          docker push amolknexaitech/potdargroupbackend:latest

          docker build -t dynamicbackend:latest ./dynamicbackend
          docker push amolknexaitech/dynamicbackend:latest

          docker build -t amolknexaitech/amolknexaitech/randomwebsite:latest .
          docker push amolknexaitech/randomwebsite:latest  ./randomwebsite

      - name: Deploy microservices
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.CICDNODE }}
        run: |
          # Deploy microservice using Docker Compose or Kubernetes, depending on your setup
          # Example:
          # docker-compose up -d
          # or
          # kubectl apply -f deployment.yaml

      - name: Run tests
        run: npm test
